### ISSUE TITLE
Question about the baseline of Table 2 in the paper

### ISSUE THREAD

**Issue by ByeonggeunKim** [00why00/Glocal#5]
Dear Authors,

I hope this message finds you well.

I wanted to extend my gratitude for the excellent implementation of the work titled "Glocal Energy-based Learning for Few-Shot Open-Set Recognition." Your paper has been a fantastic read. While going through it, I came across an intriguing aspect in Table 2 that caught my attention. Specifically, I noticed a 'baseline' that appears to outperform the conventional ProtoNet or FEAT approaches. I was wondering if you could kindly provide some information on how to obtain the numbers associated with this "baseline". Your insights would be greatly appreciated.

Thank you once again for your valuable contribution to the field, and I look forward to hearing from you.

**Comment by 00why00** [comment]
Thank you for your attention!

We use reimplemented SnaTCHer-F as our baseline. The code is [here](https://github.com/00why00/Glocal/blob/master/model/models/snatcher_f.py) and [here](https://github.com/00why00/Glocal/blob/master/model/trainer/fsor_trainer_snatcher_f.py). Since our method pays more attention to open set recognition, the difference in the classification accuracy of closed sets in Table 2 is very small, that is, our method improves the effect of open set recognition while ensuring the classification accuracy of closed sets is comparable.
