### ISSUE TITLE
how to make run

### ISSUE THREAD

**Issue by NDG-2018** [00why00/Glocal#9]
Thank you very much for your contribution, I have encountered some difficulties in replicating your code
I tried to reproduce your code and got the following error when using the miniImageNet dataset:
shutil.Error: [('model/models\\__pycache__\\glocal_energy.cpython-39.pyc', './checkpoints\\MiniImageNet-GEL-Res12-10w01s15qMiniImageNet-1-PIM-New-Energy\\20_0.5_lr0.01mul10_step_T64_bsz160_20230914_151516-NoAug-ATT-woSML-EL-sum-Pixel-Conv-top_query_5-AHC\\scripts\\models\\__pycache__\\glocal_energy.cpython-39.pyc', "[Errno 2] No such file or directory: './checkpoints\\\\MiniImageNet-GEL-Res12-10w01s15qMiniImageNet-1-PIM-New-Energy\\\\20_0.5_lr0.01mul10_step_T64_bsz160_20230914_151516-NoAug-ATT-woSML-EL-sum-Pixel-Conv-top_query_5-AHC\\\\scripts\\\\models\\\\__pycache__\\\\glocal_energy.cpython-39.pyc'"), ('model/models\\__pycache__\\__init__.cpython-39.pyc', './checkpoints\\MiniImageNet-GEL-Res12-10w01s15qMiniImageNet-1-PIM-New-Energy\\20_0.5_lr0.01mul10_step_T64_bsz160_20230914_151516-NoAug-ATT-woSML-EL-sum-Pixel-Conv-top_query_5-AHC\\scripts\\models\\__pycache__\\__init__.cpython-39.pyc', "[Errno 2] No such file or directory: './checkpoints\\\\MiniImageNet-GEL-Res12-10w01s15qMiniImageNet-1-PIM-New-Energy\\\\20_0.5_lr0.01mul10_step_T64_bsz160_20230914_151516-NoAug-ATT-woSML-EL-sum-Pixel-Conv-top_query_5-AHC\\\\scripts\\\\models\\\\__pycache__\\\\__init__.cpython-39.pyc'")]

Can't find this file error？‘__pycache__\\glocal_energy.cpython-39.pyc’

I tried to solve the problem but did not find the error message. I sincerely look forward to your reply.

**Comment by 00why00** [comment]
In fact, Python is divided into two steps when interpreting the source program:

1. Process the source code and compile it to generate a binary bytecode.
2. Process the bytecode to generate machine code that the CPU can recognize.

After having the bytecode file of the module, the next time you run the program, if the source code has not been modified since the last time the bytecode was saved, Python will load the `.pyc` file and skip the compilation step.

When Python recompiles, it automatically checks the timestamps of source files and bytecode files. If you modify the source code again, the bytecode will be automatically recreated the next time the program is run.

Generally speaking, binary bytecode files are saved in the `__pycache__` folder. For the error you mentioned, you can try the following two solutions:

1. Rename the `pycache` folder to `__pycache__`.
2. Delete the `pycache` folder and let Python regenerate binary bytecode.

**Comment by NDG-2018** [comment]
Thank you very much for your answer, tiaoxiao. According to your help, I have solved the data problem. Please allow me to ask your graphics card device again. I use 3060, 12G graphics memory, and I reported the following error when running miniImageNet: RuntimeError: CUDA out of memory. Tried to allocate 174.00 MiB (GPU 0; 12.00 GiB total capacity; 10.69 GiB already allocated; 0 bytes free;  11.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid  fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Is this a problem with my equipment, I put self.grab_gpu = torch.zeros([1024, 1024, 1024], As dtype=torch.double).cuda() becomes smaller and episodes_per_epoch and num_eval_episodes are turned down, they still can't run. My code isn't very good. Thank you very much for your patience.

**Comment by 00why00** [comment]
We used the Nvidia 3090 with 24G memory to train the model. As mentioned in your error, the 3060 with only 12G memory failed to run due to exceeding the memory limit. Please try to use a GPU device with larger memory to run our model.
